INSERT INTO `diputados_diputado`(nombre, apellidos, sexo, tipo, fotografia, email, telefono, sede, status, legislatura_id, partido_id)  
VALUES ('Alejandra Guadalupe','Esquitín Lastirí',2,1,'diputados/fotos/ALEJANDRA_GUADALUPE_ESQUITIN_LASTIRI.jpg','dip.alejandra.esquitin@congresopuebla.gob.mx','22237721100',2,1,1,6),
('Liliana','Luna Aguirre',2,1,'diputados/fotos/LILIANA_LUNA_AGUIRRE.jpg','dip.liliana.luna@congresopuebla.gob.mx','(222) 372 1100 Ext. 167',2,1,1,4),
('Raúl','Espinosa Martínez',1,1,'diputados/fotos/RAUL_ESPINOSA_MARTINEZ.jpg','dip.raul.espinosa@congresopuebla.gob.mx','176',2,1,1,2),
('Hugo','Alejo Domínguez',1,1,'diputados/fotos/HUGO_ALEJO_DOMINGUEZ.jpg','dip.hugo.alejo@congresopuebla.gob.mx','152',2,1,1,NULL),
('Nancy','Jiménez Morales',2,1,'diputados/fotos/NANCY_JIMENEZ_MORALES.jpg','dip.nancy.jimenez@congresopuebla.gob.mx','165',2,1,1,2),
('María del Carmen','Saavedra Fernández',2,1,'diputados/fotos/MARIA_DEL_CARMEN_SAAVEDRA_FERNANDEZ.jpg','dip.mariadelcarmen.saavedra@congresopuebla.gob.mx','217',2,1,1,1),
('Bárbara Dimpna','Morán Añorve',2,1,'diputados/fotos/BARBARA_DIMPNA_MORAN_ANORVE.jpg','dip.barbara.moran@congresopuebla.gob.mx','162',1,1,1,1),
('Rafaela Vianey','García Romero',2,1,'diputados/fotos/RAFAELA_VIANEY_GARCIA_ROMERO.jpg','dip.vianey.garcia@congresopuebla.gob.mx','223',1,1,1,1),
('Delfina Leonor','Vargas Gallegos',2,1,'diputados/fotos/DELFINA_LEONOR_VARGAS_GALLEGOS.jpg','dip.delfina.vargas@congresopuebla.gob.mx','185',1,4,1,1),
('Nora Yessica','Merino Escamilla',2,1,'diputados/fotos/NORA_YESSICA_MERINO_ESCAMILLA.jpg','dip.nora.merino@congresopuebla.gob.mx','185',1,1,1,1),
('Emilio Ernesto','Maurer Espinosa',1,1,'diputados/fotos/EMILIO_ERNESTO_MAURER_ESPINOSA.jpg','dip.emilio.maurer@congresopuebla.gob.mx','231',1,1,1,1),
('José Miguel','Trujillo de Ita',1,1,'diputados/fotos/JOSE_MIGUEL_TRUJILLO_DE_ITA.jpg','dip.miguel.trujillo@congresopuebla.gob.mx','128',1,1,1,8),
('Raymundo','Atanacio Luna',1,1,'diputados/fotos/RAYMUNDO_ATANACIO_LUNA.jpg','dip.raymundo.atanacio@congresopuebla.gob.mx','196',1,1,1,9),
('Uruviel','González Vieyra',1,1,'diputados/fotos/URUVIEL_GONZALEZ_VIEYRA.jpg','dip.uruviel.gonzalez@congresopuebla.gob.mx','161',2,1,1,7),
('Arturo','de Rosas Cuevas',1,1,'diputados/fotos/ARTURO_DE_ROSAS_CUEVAS.jpg','dip.arturoderosas@congresopuebla.gob.mx','194',1,1,1,9),
('Yadira','Lira Navarro',2,1,'diputados/fotos/YADIRA_LIRA_NAVARRO.jpg','dip.yadira.lira@congresopuebla.gob.mx','187',1,4,1,1),
('Mónica','Lara Chávez',2,1,'diputados/fotos/MONICA_LARA_CHAVEZ.jpg','dip.monica.lara@congresopuebla.gob.mx','148',1,1,1,8),
('Tonantzin','Fernández Díaz',2,1,'diputados/fotos/TONANTZIN_FERNANDEZ_DIAZ.jpg','dip.tonantzin.fernandez@congresopuebla.gob.mx','171',1,1,1,1),
('Héctor Eduardo','Alonso Granados',1,1,'diputados/fotos/HECTOR_EDUARDO_ALONSO_GRANADOS.jpg','dip.hector.alonso@congresopuebla.gob.mx','156',1,1,1,6),
('José Juan','Espinosa Torres',1,1,'diputados/fotos/JOSE_JUAN_ESPINOSA_TORRES.jpg','dip.jose.espinosa@congresopuebla.gob.mx','129',1,1,1,9),
('Guadalupe','Muciño Muñoz',2,1,'diputados/fotos/GUADALUPE_MUCINO_MUNOZ.jpg','dip.guadalupe.mucino@congresopuebla.gob.mx','235',1,1,1,9),
('Ángel Gerardo','Islas Maldonado',1,1,'diputados/fotos/ANGEL_GERARDO_ISLAS_MALDONADO.jpg','dip.angel.islas@congresopuebla.gob.mx','117',2,1,1,10),
('Nibardo','Hernández Sánchez',1,1,'diputados/fotos/NIBARDO_HERNANDEZ_SANCHEZ.jpg','dip.nibardo.hernandez@congresopuebla.gob.mx','177',2,1,1,3),
('Fernando','Sánchez Sasia',1,1,'diputados/fotos/FERNANDO_SANCHEZ_SASIA.jpg','dip.fernando.sanchez@congresopuebla.gob.mx','179',1,1,1,1),
('Olga Lucía','Romero Garci Crespo',2,1,'diputados/fotos/OLGA_LUCIA_ROMERO_GARCI-CRESPO.jpg','dip.olga.romero@congresopuebla.gob.mx','0',1,1,1,1),
('José Armando','García Avendaño',1,1,'diputados/fotos/JOSE_ARMANDO_GARCIA_AVENDANO.jpg','dip.armando.garcia@congresopuebla.gob.mx','141',2,1,1,4),
('Gabriel Juan Manuel','Biestro Medinilla',1,2,'diputados/fotos/GABRIEL_JUAN_MANUEL_BIESTRO_MEDINILLA.jpg','dip.gabriel.biestro@congresopuebla.gob.mx','175',1,1,1,1),
('Estefanía','Rodríguez Sandoval',2,2,'diputados/fotos/ESTEFANIA_RODRIGUEZ_SANDOVAL.jpg','dip.estefania.rodriguez@congresopuebla.gob.mx','230',1,1,1,1),
('Luis Fernando','Jara Vargas',1,2,'diputados/fotos/LUIS_FERNANDO_JARA_VARGAS.jpg','dip.luis.jara@congresopuebla.gob.mx','142',1,1,1,1),
('Cristina','Tello Rosas',2,2,'diputados/fotos/CRISTINA_TELLO_ROSAS.jpg','dip.cristina.tello@congresopuebla.gob.mx','227',1,1,1,1),
('María del Carmen','Cabrera Camacho',2,2,'diputados/fotos/MARIA_DEL_CARMEN_CABRERA_CAMACHO.jpg','dip.mariadelcarmen.camacho@congresopuebla.gob.mx','179',1,1,1,9),
('Valentín','Medel Hernández',1,2,'diputados/fotos/VALENTIN_MEDEL_HERNANDEZ.jpg','dip.valentin.medel@congresopuebla.gob.mx','233',1,1,1,9),
('Javier','Casique Zárate',1,2,'diputados/fotos/JAVIER_CASIQUE_ZARATE.jpg','dip.javier.casique@congresopuebla.gob.mx','0',2,1,1,3),
('Josefina','García Hernández',2,2,'diputados/fotos/JOSEFINA_GARCIA_HERNANDEZ.jpg','dip.josefina.garcia@congresopuebla.gob.mx','234',1,1,1,3),
('María del Rocío','García Olmedo',2,2,'diputados/fotos/MARIA_DEL_ROCIO_GARCIA_OLMEDO.jpg','dip.mariadelrocio.garcia@congresopuebla.gob.mx','158',1,1,1,3),
('Mónica','Rodríguez Della Vecchia',2,2,'diputados/fotos/MONICA_RODRIGUEZ_DELLA_VECCHIA.jpg','dip.monica.rodriguez@congresopuebla.gob.mx','149',2,1,1,2),
('Gabriel Oswaldo','Jiménez López',1,2,'diputados/fotos/GABRIEL_OSWALDO_JIMENEZ_LOPEZ.jpg','dip.oswaldo.jimenez@congresopuebla.gob.mx','160',2,1,1,2),
('Carlos Alberto','Morales Álvarez',1,2,'diputados/fotos/CARLOS_ALBERTO_MORALES_ALVARES.jpg','dip.carlos.morales@congresopuebla.gob.mx','193',2,1,1,6),
('Juan Pablo','Kuri Carballo',1,2,'diputados/fotos/JUAN_PABLO_KURI_CARBALLO.jpg','dip.juan.kuri@congresopuebla.gob.mx','182',1,1,1,5),
('Iván Jonathan','Collantes Cabañas',1,2,'diputados/fotos/IVAN_JONATHAN_COLLANTES_CABANAS.jpg','dip.jonathan.collantes@congresopuebla.gob.mx','163',2,1,1,NULL),
('Marcelo Eugenio','García Almaguer',1,2,'diputados/fotos/MARCELO_EUGENIO_GARCIA_ALMAGUER.jpg','dip.marcelo.garcia@congresopuebla.gob.mx','174',2,1,1,NULL),
('José Luis','Rosas Quiñones',1,1,'','dip.joseluis.rosas@congresopuebla.mx','0',1,2,1,10),
('Guadalupe','Tlaque Cuazitl',2,1,'diputados/fotos/GUADALUPE_TLAQUE_CUAZITL.jpg','dip.guadalupe.tlaque@congresopuebla.mx','170',1,1,1,1),
('Iliana Paola','Ruíz García',2,1,'diputados/fotos/ILIANA_PAOLA_RUIZ_GARCIA.jpg','dip.paola.ruiz@congresopuebla.gob.mx','187',1,1,1,1);

INSERT INTO `diputados_comision` (nombre) VALUES 
('Comisión de Pueblos Indígenas'),
('Comisión de Asuntos Metropolitanos'),
('Comisión de Asuntos Municipales'),
('Comisión de Atención a Personas con Discapacidad'),
('Comisión de Ciencia y Tecnología'),
('Comisión de Comunicaciones e Infraestructura'),
('Comisión de Cultura'),
('Comisión de Derechos Humanos'),
('Comisión de Desarrollo Económico'),
('Comisión de Desarrollo Rural'),
('Comisión de Bienestar'),
('Comisión de Desarrollo Urbano'),
('Comisión de Educación'),
('Comisión de la Familia y los Derechos de la Niñez'),
('Comisión de Gobernación y Puntos Constitucionales'),
('Comisión de Grupos Vulnerables'),
('Comisión de Hacienda y Patrimonio Municipal'),
('Comisión de Igualdad de Género'),
('Comisión Inspectora de la Auditoría Superior del Estado'),
('Comisión Instructora'),
('Comisión de Juventud y Deporte'),
('Comisión de Medio Ambiente, Recursos Naturales y Cambio Climático'),
('Comisión de Migración y Asuntos Internacionales'),
('Comisión de Organizaciones No Gubernamentales'),
('Comisión de Participación Ciudadana y Combate a la Corrupción'),
('Comisión de Presupuesto y Crédito Público'),
('Comisión de Procuración y Administración de Justicia'),
('Comisión de Protección Civil'),
('Comisión de Salud'),
('Comisión de Seguridad Pública'),
('Comisión de Trabajo, Competitividad y Previsión Social'),
('Comisión de Transparencia y Acceso a la Información'),
('Comisión de Transportes y Movilidad'),
('Comisión de Turismo'),
('Comisión de Vivienda'),
('Comisión Especial para el Análisis y Seguimiento de la Elección a Gobernador del Estado de Puebla'),
('Comisión Especial de seguimiento de las labores de reconstrucción derivadas de los sismos del 2017'),
('Comité de Adquisiciones, Arrendamientos y Servicios'),
('Comité de Atención Ciudadana'),
('Comité de Comunicación Social'),
('Comité de Diario de Debates, Crónica Legislativa y Asuntos Editoriales'),
('Comité de Innovación y Tecnología'),
('Comisión Especial de Pueblos Mágicos para su Desarrollo Económico, Turístico y Social');

INSERT INTO `diputados_distrito` (numero,nombre,status) VALUES 
(1,'Xicotepec de Juárez',1),
(2,'Huauchinango de Degollado',1),
(3,'Zacatlán',1),
(4,'Zacapoaxtla',1),
(5,'Tlatlauquitepec',1),
(6,'Teziutlán',1),
(7,'San Martín Texmelucan de Labastida',1),
(8,'Huejotzingo',1),
(9,'Heroica Puebla de Zaragoza',1),
(10,'Heroica Puebla de Zaragoza',1),
(11,'Heroica Puebla de Zaragoza',1),
(12,'Amozoc de Mota',1),
(13,'Tepeaca',1),
(14,'Ciudad Serdán',1),
(15,'Tecamachalco',1),
(16,'Heroica Puebla de Zaragoza',1),
(17,'Heroica Puebla de Zaragoza',1),
(18,'Heroica Puebla de Zaragoza',1),
(19,'Heroica Puebla de Zaragoza',1),
(20,'Heroica Puebla de Zaragoza',1),
(21,'Atlixco',1),
(22,'Izúcar de Matamoros',1),
(23,'Acatlán de Osorio',1),
(24,'Tehuacán',1),
(25,'Tehuacán',1),
(26,'Ajalpan',1);
