# Generated by Django 3.0.3 on 2020-03-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='Diputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=0)),
                ('tipo', models.IntegerField(choices=[(1, 'Mayoría Relativa'), (2, 'Representación Proporcional')], default=1, verbose_name='Tipo de elección')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='diputados/fotos')),
                ('email', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=25)),
                ('sede', models.IntegerField(choices=[(1, '5 poniente'), (2, 'Mesón del Cristo')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Licencia menor a 30 días'), (4, 'Licencia por tiempo indefinido')], default=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='DiputadoOrganoLegislativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cargo', models.IntegerField(choices=[(1, 'PRESIDENTE(A)'), (2, 'VICEPRESIDENTE(A)'), (3, 'SECRETARIO(A)'), (4, 'PROSECRETARIO(A)'), (5, 'VOCAL'), (6, 'COORDINADOR(A)'), (7, 'REPRESENTANTE LEGISLATIVO')], verbose_name='Cargo')),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('diputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
            options={
                'verbose_name_plural': 'Integrantes',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.IntegerField(choices=[(1, 'INFORME'), (2, 'PLAN DE TRABAJO'), (3, 'INICIATIVA'), (4, 'PUNTO DE ACUERDO'), (5, 'DICTAMEN'), (6, 'OTRO')], verbose_name='Tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fin', models.DateField(verbose_name='Fecha de termino')),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partidos/logos')),
            ],
            options={
                'verbose_name_plural': 'Partidos Políticos',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de sesión')),
                ('url_acta_sesion', models.FileField(blank=True, null=True, upload_to='sesiones/actas', verbose_name='Acta de la sesión')),
                ('url_orden_dia', models.FileField(blank=True, null=True, upload_to='sesiones/orden_dia', verbose_name='Orden del día')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.IntegerField(choices=[(1, 'Abrobada'), (2, 'No aprobada')])),
                ('tipo', models.IntegerField(choices=[(1, 'Nominal'), (2, 'Economica'), (3, 'Secreta')], verbose_name='Tipo de votación')),
            ],
        ),
        migrations.CreateModel(
            name='DiputadoIndependiente',
            fields=[
                ('diputado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diputados.Diputado')),
                ('es_independiente', models.BooleanField()),
            ],
            bases=('diputados.diputado',),
        ),
        migrations.CreateModel(
            name='SesionPleno',
            fields=[
                ('sesion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diputados.Sesion')),
                ('tipo', models.IntegerField(choices=[(0, 'SESIÓN PREVÍA'), (1, 'PÚBLICA ORDINARIA'), (2, 'SESIÓN EXTRAORDINARIA'), (3, 'COMISIÓN PERMANENTE'), (4, 'SESIÓN SOLEMNE')], default=1, verbose_name='Tipo de sesión')),
                ('url_version_estenografica', models.FileField(blank=True, null=True, upload_to='sesiones/version_esteno', verbose_name='Versión estenográfica')),
            ],
            options={
                'verbose_name': 'Sesión de Pleno',
                'verbose_name_plural': 'Sesiones de Pleno',
            },
            bases=('diputados.sesion',),
        ),
        migrations.CreateModel(
            name='VotacionSecreta',
            fields=[
                ('votacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diputados.Votacion')),
                ('votos_favor', models.IntegerField(default=0, verbose_name='Votos a favor')),
                ('votos_contra', models.IntegerField(default=0, verbose_name='Votos en contra')),
                ('abstenciones', models.IntegerField(default=0, verbose_name='Abstenciones')),
            ],
            bases=('diputados.votacion',),
        ),
        migrations.CreateModel(
            name='VotoDiputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.IntegerField(choices=[(1, 'A FAVOR'), (2, 'EN CONTRA'), (3, 'EN ABSTENCION'), (4, 'SECRETA')], verbose_name='Tipo de voto')),
                ('diputado', models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Votacion')),
            ],
        ),
        migrations.AddField(
            model_name='votacion',
            name='diputado',
            field=models.ManyToManyField(through='diputados.VotoDiputado', to='diputados.Diputado'),
        ),
        migrations.AddField(
            model_name='votacion',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diputados.Tema'),
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('url', models.URLField()),
                ('diputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
        ),
        migrations.CreateModel(
            name='OrganoLegislativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.IntegerField(choices=[(1, 'Junta de Gobierno y Coordinación Política'), (2, 'Mesa Directiva'), (3, 'Comisión Permanente')])),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado')),
                ('inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fin', models.DateField(verbose_name='Fecha de termino')),
                ('integrantes', models.ManyToManyField(through='diputados.DiputadoOrganoLegislativo', to='diputados.Diputado')),
                ('legislatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diputados.Legislatura')),
            ],
            options={
                'verbose_name_plural': 'Órganos Legislativos',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Inicio de licencia')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Termino de licencia')),
                ('tipo', models.IntegerField(choices=[(1, 'Menor a 30 días'), (2, 'Tiempo Indefinido')], verbose_name='Tipo de licencia')),
                ('diputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('diputado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distrito', to='diputados.Diputado', verbose_name='Representante')),
            ],
        ),
        migrations.CreateModel(
            name='DiputadoSuplente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('diputado_propietario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propietario', to='diputados.Diputado')),
                ('diputado_suplente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suplente', to='diputados.Diputado')),
            ],
        ),
        migrations.AddField(
            model_name='diputadoorganolegislativo',
            name='organo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.OrganoLegislativo'),
        ),
        migrations.AddField(
            model_name='diputado',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diputados.Legislatura'),
        ),
        migrations.AddField(
            model_name='diputado',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diputados.PartidoPolitico', verbose_name='Partido Político'),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_academicos', models.TextField(verbose_name='Datos Académicos')),
                ('datos_laborales', models.TextField(verbose_name='Datos Laborales')),
                ('otros_datos', models.TextField(verbose_name='Otros datos')),
                ('diputado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
        ),
        migrations.CreateModel(
            name='ComisionDiputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cargo', models.IntegerField(choices=[(1, 'PRESIDENTE(A)'), (2, 'SECRETARIO(A)'), (3, 'VOCAL')], verbose_name='Cargo')),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Comision')),
                ('diputado', models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
            options={
                'verbose_name_plural': 'Ingrantes de la Comisión',
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='diputado',
            field=models.ManyToManyField(through='diputados.ComisionDiputado', to='diputados.Diputado'),
        ),
        migrations.CreateModel(
            name='CasaGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('diputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asistencia', models.IntegerField(choices=[(1, 'ASISTENCIA'), (2, 'INASISTENCIA JUSTIFICADA'), (3, 'INASISTENCIA INJUSTIFICADA'), (4, 'RETARDO JUSTIFICADO'), (5, 'RETARDO INJUSTIFICADO')], default=1, verbose_name='Tipo de asistencia')),
                ('diputado', models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Sesion')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='SesionComision',
            fields=[
                ('sesion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diputados.Sesion')),
                ('url_comunicado', models.FileField(blank=True, null=True, upload_to='comisiones/comunicados', verbose_name='Comunicado')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Comision')),
            ],
            options={
                'verbose_name_plural': 'Sesiones de Comisión',
            },
            bases=('diputados.sesion',),
        ),
        migrations.CreateModel(
            name='DocumentoSesion',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diputados.Documento')),
                ('url_documento', models.FileField(upload_to='sesiones/<django.db.models.fields.related.ForeignKey>/documento', verbose_name='Documento')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Tema')),
            ],
            bases=('diputados.documento',),
        ),
        migrations.CreateModel(
            name='DocumentoDiputado',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diputados.Documento')),
                ('url_documento', models.FileField(upload_to='diputados/<django.db.models.fields.related.ForeignKey>/documento', verbose_name='Documento')),
                ('diputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
            bases=('diputados.documento',),
        ),
        migrations.CreateModel(
            name='DocumentoComision',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diputados.Documento')),
                ('url_documento', models.FileField(upload_to='comisiones/<django.db.models.fields.related.ForeignKey>/documento', verbose_name='Documento')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Comision')),
            ],
            bases=('diputados.documento',),
        ),
    ]
